<h1>Editar Aluno</h1>
<hr>

<form action="" method="post">
    <input type="hidden" name="id" value="<?php echo $dados['id'];?>">
    <label for="">Nome</label>
    <input type="text" name="nome" value="<?php echo $_POST['nome'] ?? $dados['nome'];?>">
    <label for="">Matricula</label>
    <input type="text" name="matricula" value="<?php echo $_POST['matricula'] ?? $dados['matricula'];?>">
    <label for="">Cidade</label>
    <input type="text" name="cidade" value="<?php echo $_POST['cidade'] ?? $dados['cidade'];?>">
    <button type="submit">Editar</button>
</form>

