<h1>Editar Aluno</h1>
<hr>

<form action="" method="post">
    <input type="hidden" name="id" value="<?php echo $aluno['id'];?>">
    <label for="">Nome</label>
    <input type="text" name="nome" value="<?php echo $aluno['nome'];?>">
    <label for="">Matricula</label>
    <input type="text" name="matricula" value="<?php echo $aluno['matricula'];?>">
    <label for="">Cidade</label>
    <input type="text" name="cidade" value="<?php echo $aluno['cidade'];?>">
    <button type="submit">Editar</button>
</form>

