
<h1>Página de Cadastro</h1>

<hr>

<form action="" method="post">
    <label for="">Nome</label>
    <input required value="<?php echo $_POST['nome'] ?? '' ?>" type="text" name="nome">

    <label for="">Matricula</label>
    <input required value="<?php echo $_POST['matricula'] ?? '' ?>" type="text" name="matricula">

    <label for="">Cidade</label>
    <input required value="<?php echo $_POST['cidade'] ?? '' ?>" type="text" name="cidade">

    <button type="submit">Criar</button>
</form>

